SET OKTA_CLIENT_ID=
SET OKTA_CLIENT_SECRET=
SET OKTA_ISSUER_URI=
SET KEYVAULT_URI=https://advworkkv01.vault.azure.net/
SET KEYVAULT_CLIENT_ID=
SET KEYVAULT_TENANT_ID=
SET KEYVAULT_KEY=
java -jar ./target/aw-sb-okta-0.0.1-SNAPSHOT.jar