# `spring.datasource.url` should be in the form of
# jdbc:sqlserver://{host}:{port};database={db};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring:
  datasource:
    url: jdbc:sqlserver://${SQL_HOST:localhost}:${SQL_PORT:1433};databaseName=${SQL_DBNAME:AdventureWorksLT2017};
    username: ${SQL_USERNAME:sa}
    password: ${SQL_PASSWORD:Password_01}
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  profiles:
    active: @spring.profiles.active@
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 
            client-secret: 
            scope: openid, email, profile
        provider:
          okta:
            issuer-uri: 